App\Entity\Quiz:
    constraints:
        - App\Validator\Constraints\AlmostOneQuestion: ~
        - App\Validator\Constraints\DisableQuizFinalized: ~
    properties:
        name:
            - NotNull: ~
            - Type: string
            - Length:
                max: 40
        description:
            - Type: string
            - Length:
                max: 110
        status:
            - NotNull: ~
            - Choice:
                choices: [pending, finalized]

App\Entity\Question:
    constraints:
        - App\Validator\Constraints\DisableQuizFinalized: ~
    properties:
        label:
            - NotNull: ~
            - Type: string
            - Length:
                max: 300
        type:
            - NotNull: ~
            - Choice:
                  choices: [duo, carre, qcm]
        position:
            - NotNull: ~
            - Type: integer

App\Entity\Proposition:
    constraints:
        - App\Validator\Constraints\DisableQuizFinalized: ~
    properties:
        label:
            - Type: string
            - Length:
                max: 150
        wrightAnswer:
            - Type: bool
        position:
            - NotNull: ~
            - Type: integer

App\Entity\User:
    properties:
        email:
            - Email:
                message: Not a valid email.

App\Entity\Invitation:
    properties:
        email:
            - Email:
                  message: Not a valid email.

App\Entity\Answer:
    properties:
        propositions:
            - Valid: ~
